name: PUsh Image to docker Hub

on:
  push:
    branches:
      - main

jobs:
  push-to-registry:
    name: push-image-to-github
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Dokcer Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Extract meta information
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: hafizpustic/laravel-demo-cicd
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: ./php
          file: ./php/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
