name: Laravel CI UNIT Test

on: [push, pull_request] # Runs on push & pull requests

jobs:
  test:
    runs-on: ubuntu-latest # Use Ubuntu as the environment

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Pulls the repository code

      - name: Set Up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3" # Set PHP version
          extensions: mbstring, pdo, pdo_mysql # Add necessary extensions
          coverage: none # Disable Xdebug unless needed

      - name: Install Composer Dependencies
        run: cd src && cp .env.example .env && composer install

      - name: Run Tests
        run: cd src && php artisan test
